
name: Runnings test on push to main

on:
  push:
    branches: [ "main" ]



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.4
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.4"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Run test cases
      run: pytest test_prediction.py
       
